# Generated by Django 2.1.4 on 2018-12-20 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_full_name', models.CharField(db_column='Full Name', max_length=64)),
                ('student_reg_no', models.CharField(db_column='Registration Number', max_length=64)),
                ('student_password', models.CharField(db_column='Password', max_length=64)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('students_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_joined',),
            },
        ),
    ]
