# Generated by Django 2.1.4 on 2018-12-21 08:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wordgameapi', '0002_auto_20181221_1622'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('student_reg_no', 'students_teacher')},
        ),
    ]
