# Generated by Django 2.1.4 on 2018-12-20 06:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('teacher_full_name', models.CharField(db_column='Full Name', max_length=64)),
                ('teacher_school_name', models.CharField(db_column='School Name', max_length=128, null=True)),
                ('teacher_email', models.EmailField(db_column='Email Address', db_index=True, max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ('-date_joined',),
            },
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_word', models.CharField(help_text='Word in english', max_length=64)),
                ('chinese_word', models.TextField(help_text='chinese translation')),
                ('pinyin_word', models.TextField(help_text='pinyin translation')),
                ('pronunciation_ipa', models.CharField(max_length=96)),
                ('word_audio', models.FileField(help_text='upload the audio for pronunciation', upload_to='EnglishWords')),
            ],
            options={
                'verbose_name_plural': 'Words',
            },
        ),
    ]
