# Generated by Django 2.1.4 on 2018-12-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordgameweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_school_name',
            field=models.CharField(blank=True, db_column='School Name', max_length=128, null=True),
        ),
    ]
