# Generated by Django 2.1.4 on 2018-12-21 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wordgameweb', '0002_auto_20181221_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachersList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_number', models.PositiveSmallIntegerField(db_column='List Number')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('words', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordgameweb.Words')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='teacherslist',
            unique_together={('list_number', 'created_by', 'words')},
        ),
    ]
